name: Training Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: '0 2 * * *'   # every day at 2am UTC
  workflow_dispatch:        

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup GCP credentials
        run: |
          echo '${{ secrets.GCP_KEY_JSON }}' > gcp-key.json
      - name: Run training pipeline
        env:
          GOOGLE_CLOUD_PROJECT: aqi-predictor-497110
          GOOGLE_CLOUD_REGION: us-central1
          GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
        run: python training_pipeline.py